### ISSUE TITLE
Cant find DropExtremeLabel processer

### ISSUE THREAD

**Issue by chenchao08000** [SJTU-DMTai/MASTER#19]
Well,I didnt find any DropExtremeLabel processer even in official Qlib repo or your forked Qlib repo?

**Comment by LITONG99** [comment]
You may want to read [An Alternative Implementation](https://github.com/SJTU-DMTai/MASTER?tab=readme-ov-file#an-alternative-qlib-implementation) in the Readme.

**Comment by chenchao08000** [comment]
Thank you very much
