### ISSUE TITLE
Wonder what are the hyperparameters for the metrics results shown in the paper?

### ISSUE THREAD

**Issue by TompaBay** [SJTU-DMTai/MASTER#20]
I ran the models using hyperparameters told in the paper (nheads, temperature, dmodel), and get similar results on IC and ICIR. But the RankIC and RankICIR never get closed to the level shown in the paper. The RankIC was always around 0.060, which was lower than 0.076 for CSI300 shown in the paper. Besides, RankIC was typically lower than IC when I ran Master, so I wonder if it's possible for you to disclose the specific hyperparameters setting? Thanks!

**Comment by LITONG99** [comment]
Hi, please adhere to the paper's descriptions on hyperparameters as they faithfully record our experiments. 

I ran the code five times (seeds 0-4) using the hyperparameters from the paper on my laptop with torch==2.4.0+cu121. Based on this trial, RankIC was not typically lower than IC but I also realize the values of RankIC are noticeably lower than that in the paper. Unfortunately, I cannot probe the specific reason as I do not store and maintain the extract replica of the original codebase or the environment. Despite different statistical values, I analyzed the results and they also agree with the main conclusions we made in the paper. 

I have attached my results here for anyone who would find them helpful in the future. Overall, if you get results similar to those I listed here, then everything goes normally for MASTER. 

**CSI300**
IC: 0.066 pm 0.003
ICIR: 0.45 pm 0.03
RankIC: 0.067 pm 0.002
RankICIR: 0.46 pm 0.03

**CSI800**
IC: 0.059 pm 0.002
ICIR: 0.47 pm 0.02
RankIC: 0.059 pm 0.004
RankICIR: 0.47 pm 0.03

**Comment by LITONG99** [comment]
Please check on the update.
